"""
Django settings for site_card project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import environ
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = env.bool('DEBUG')

ALLOWED_HOSTS = [
    'hypno-consult.com.ua',  # основний домен
    'www.hypno-consult.com.ua',  # якщо використовується з www
    '127.0.0.1',
    'localhost',
]


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app_main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'app_main.middlewares.VisitorLoggingMiddleware',  # прослойка для трекінгу користувачів, збір інфи про них
    'django.middleware.locale.LocaleMiddleware',  # для вибору мови
]

ROOT_URLCONF = 'site_card.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "site_card" / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app_main.context_processors.contact_info'
            ],
        },
    },
]

WSGI_APPLICATION = 'site_card.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

TIME_ZONE = 'UTC'
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # важливо для Render
# Де шукати додаткові статичні файли
STATICFILES_DIRS = [
    BASE_DIR / "static/",
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} [{name}] {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'errors.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'error_file'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}

# налаштування безпеки для продакшину
if not DEBUG:  # тільки якщо сайт вже працює на HTTPS    
    # наказує браузеру завжди використовувати HTTPS, навіть якщо користувач вів http
    SECURE_HSTS_SECONDS = 31536000  # 1 рік у секундах
    # включає всі піддомени (наприклад, www.hypno-consult.com.ua`, `blog.hypno-consult.com.ua`).
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # Автоматично перенаправляє з HTTP → HTTPS
    SECURE_SSL_REDIRECT = True
    # Змушує cookie з сесією передаватися лише через HTTPS. Захищає від крадіжки сесій через MITM-атаки
    SESSION_COOKIE_SECURE = True
    # Те саме, але для **CSRF-токена**, який Django використовує для захисту форм
    CSRF_COOKIE_SECURE = True

PHONE = env('CONTACT_PHONE')
EMAIL = env('CONTACT_EMAIL')
TELEGRAM_USERNAME = env('CONTACT_TELEGRAM')
VIBER_PHONE = env('CONTACT_VIBER')

GEOLITE_FILE = BASE_DIR.parent / 'db/GeoLite2-City.mmdb'

#  налаштування для вибору мови
LANGUAGE_CODE = 'uk'
USE_I18N = True

LANGUAGES = [
    ('uk', 'Українська'),
    ('ru', 'Русский'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']
